language: java
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
install: ant init
script: ant build.modules
=======
script: ant debug
<<<<<<< HEAD
>>>>>>> f45152d... Travis
=======
#script: ant debug
>>>>>>> 1f2f053... test
=======
script: ant debug
>>>>>>> d0aacea... oups
=======
=======
script: ant debug
>>>>>>> aaeb627... Revert "ok"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
<<<<<<< HEAD
>>>>>>> e8dcc8d... Update .travis.yml
=======
script: ant debug
>>>>>>> a1a5b63... ok
=======
>>>>>>> aaeb627... Revert "ok"
